Handle settings in guix store

diff --git a/bin/genenetwork2 b/bin/genenetwork2
--- a/bin/genenetwork2
+++ b/bin/genenetwork2
@@ -11,12 +11,15 @@ SCRIPT=$(readlink -f "$0")
 GN2_BASE_PATH=$(dirname $(dirname "$SCRIPT"))
 echo $GN2_BASE_PATH
 
-# Handle setting parameter
+# Handle settings parameter
 settings=$1
 if [ -z $settings ]; then settings=$GN2_BASE_PATH/etc/default_settings.py ; fi
 if [ ! -e $settings ]; then
-    echo "ERROR: can not load settings file $settings"
-    exit 1
+    settings=$GN2_BASE_PATH/lib/python2.7/site-packages/genenetwork2-2.0-py2.7.egg/etc/default_settings.py
+    if [ ! -e $settings ]; then
+        echo "ERROR: can not locate settings file - pass it in the command line"
+        exit 1
+    fi
 fi
 export WQFLASK_SETTINGS=$settings
 
